### ISSUE TITLE
Error con Simple Row

### ISSUE THREAD

**Issue by fabricioflores** [Silverhill/coupon-components#47]
Cuando envías un objeto que no tenga todas las características, se cae.
PD: los datos q vienen del backend con sus nombres:
<img width="274" alt="captura de pantalla 2018-03-05 a la s 11 09 57" src="https://user-images.githubusercontent.com/3495122/36985635-cdf6603e-2065-11e8-8317-099ae98d5d64.png">

**Comment by leninkp** [comment]
Gracias ya lo reviso

**Comment by leninkp** [comment]
tengo asi la data
```
const data = {
  user: {
    image: 'https://i.pinimg.com/originals/11/0f/00/110f0057f178a5f1357925aad67a9dd4.png',
    name: 'Jhon Snow',
    email: 'jhonsnow@winterfall.com'
  },
  cupon: {
    date: '19/12/2017',
    total: 50
  }
}
```

**Comment by fabricioflores** [comment]
<img width="314" alt="captura de pantalla 2018-03-05 a la s 11 15 37" src="https://user-images.githubusercontent.com/3495122/36985938-9a616704-2066-11e8-9058-4b53b89e7973.png">
data de coupons

**Comment by mvinan** [comment]
@leninkp igualmente deberías controlar que el componente no se caiga cuando una propiedad no exista. Así si yo quiero podría colocar el componente sin la fecha del último cupón, por decirlo de esa manera. Y debería funcionar todo correcto.

**Comment by mvinan** [comment]
En ese caso es mejor que el componente no reciba toda la data de golpe en un objeto es mejor en props separadas, también es más fácil para tí controlar si esa propiedad no existe. Y si haces algo así agrega algo de documentación para la implementación como aquí puse una nota:

https://silverhill.github.io/coupon-components/?selectedKind=Atoms%2FTooltip&selectedStory=Width%20triggers&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs

**Comment by leninkp** [comment]
entonces voy a ponerlos como props

**Comment by mvinan** [comment]
@leninkp y @fabricioflores Igualmente la idea del los componentes es que muestren la información que reciban y en caso de no tener data el componente solo no debe mostrarla sin que se produzca un error. La lógica de como llegue la data y moldearla a como el componente recibe ya depende de la persona que esta implementado el componente en su proyecto.
